### ISSUE TITLE
Do you still have any interest in maintaining/building gobble?

### ISSUE THREAD

**Issue by vendion** [falconindy/gobble#1]
Seeing as how you're last commit for `gobble` was from 2010 I didn't know if you still had any interest in maintaining it.  If so I created a fork and brought it up to Go 1.x standards, [vendion/gobble](https://github.com/vendion/gobble), and I would be happy to create a pull request if so (there are a few things that would need cleaned up first such as I setup Travis and added version information which isn't in your version.).  If you are no longer interested in the project that is fine as well.

Also sorry for the Issue spam regarding this, I wasn't sure the best way to contact you over this was.

**Comment by falconindy** [comment]
Hi, Gobble is pretty much obsolete. I wrote paccache instead, which includes all of the features (and more!) which are present in Gobble. It's distributed with pacman, so you likely already have it installed.
